### ISSUE TITLE
Not updating the list 

### ISSUE THREAD

**Issue by cybergeekgyan** [kuutsav/LeetComp#53]
LeetComp is not updating the list as the last date on which it was updated is 30th July 2022, 
Would be great if you could look into the matter

Thanks for the Awesome work @kuutsav .. would Love to add more functionality to it and make it more promising in near future

**Comment by kuutsav** [comment]
It's updated now. Will setup a action to update it regularly, soon.

**Comment by cybergeekgyan** [comment]
Definitely would love to help incase you need help

**Comment by ArshadAQ** [comment]
@kuutsav Seems like its not hosted now? I'm not able to access https://iutsav.dev/LeetComp/

**Comment by kuutsav** [comment]
> @kuutsav Seems like its not hosted now? I'm not able to access https://iutsav.dev/LeetComp/

@ArshadAQ It should be working now (https://kuutsav.github.io/LeetComp/). My personal domain has expired hence the redirect was failing.

**Comment by ArshadAQ** [comment]
> > @kuutsav Seems like its not hosted now? I'm not able to access https://iutsav.dev/LeetComp/
> 
> @ArshadAQ It should be working now (https://kuutsav.github.io/LeetComp/). My personal domain has expired hence the redirect was failing.

@kuutsav https://kuutsav.github.io/LeetComp/ still seems to be redirecting to your personal domain(https://iutsav.dev/LeetComp/) I guess.

**Comment by kuutsav** [comment]
> > > @kuutsav Seems like its not hosted now? I'm not able to access https://iutsav.dev/LeetComp/
> > 
> > 
> > @ArshadAQ It should be working now (https://kuutsav.github.io/LeetComp/). My personal domain has expired hence the redirect was failing.
> 
> @kuutsav Its still not working I guess.

@ArshadAQ Try to clear your cache and hosts file or try in incognito mode.

**Comment by ArshadAQ** [comment]
@kuutsav Got it, works now, thanks! I guess you would have configured a 301 redirect and not a 302 and hence its cached :)
