### ISSUE TITLE
Automate Data Update using GitHub Actions

### ISSUE THREAD

**Issue by Siddhant-K-code** [kuutsav/LeetComp#6]
*Discussion Required*

We Can Automate the Data by Setting Up the cron job (let's say for every 12hrs) using GitHub Actions.

Things We Require:
- List of Python Scripts/ Commands which would be executed.
- Env. Vars, if any

Let me know the manual process to update the data.

**Comment by kuutsav** [comment]
Sure, this will work!
Would welcome a PR

env:
PYTHONPATH (should point to the root dir)

scripts:
1. to fetch metadata for new posts
```
from leetcomp.services import get_posts_meta_info
get_posts_meta_info()
```

2. to fetch content for new posts
```
from leetcomp.services import update_posts_content_info
update_posts_content_info()
```

3. to update the inverted index for search
```
from leetcomp.inverted_index import build_inverted_index
build_inverted_index()
```

Should be create a PR from develop to master? I want to have some human verification atm.

**Comment by Siddhant-K-code** [comment]
> Should be create a PR from develop to master? I want to have some human verification atm.

didn't get this

**Comment by Siddhant-K-code** [comment]
PR will be up in this weekend.
