### ISSUE TITLE
macos setup doesn't work properly. A dockerfile would be helpful

### ISSUE THREAD

**Issue by bmbshlly** [kuutsav/LeetComp#65]

**Comment by bmbshlly** [comment]
> Thanks for the feedback. Sure, will create a dockerfile.
> 
> Can you share the error you are facing.

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==6.0)"'.

**Comment by 0xku** [comment]
Moved here https://github.com/kuutsav/leetcode-compensation
