### ISSUE TITLE
Update the DB in sync with Leetcode

### ISSUE THREAD

**Issue by shubhajitml** [kuutsav/LeetComp#66]
Please update the DB in sync with Leetcode's recent compensations.
current date - 2023/09/26
The latest compensation data visible on Leetcomp is from **2023-07-22** which is bit older.

![image](https://github.com/kuutsav/LeetComp/assets/20934378/35dc7f2b-9688-40db-a919-2c8b026aef0e)

**Comment by 0xku** [comment]
Moved here https://github.com/kuutsav/leetcode-compensation
